name: Hello World
on:
  push:
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20,x]

    steps:
      - uses: actions/checkout@v3.3.0

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            pwd
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /zelkova-front/FE
            nvm install 20
            nvm use 20
            pwd
            npm run build
  