name: when push main, merge bugfix
on:
  push:
    branches: 
      - main
jobs:
  DeployTomhoon:
    runs-on: ubuntu-latest
    steps:
      - name: After Finish Pull Request Merged 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME}}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script_stop: true
          script: |
            cd ~/../FE
            git checkout main
            git pull
            git checkout bugfix
            git merge --no-ff main -m "Merge branch 'main' into bugfix"
            git push
            git checkout main
            pwd
            node -v
            npm run build
            
      - name: Notify Discord on Success
        if: success() # Only run this step if the previous steps succeeded
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "✅ main브랜치 bugfix에 최신화 완료!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure() # Only run this step if the previous steps failed
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "❌ main브랜치 bugfix에 최신화 실패"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

