name: Hello world
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run pwd # 동작명
      run: pwd # 실제 동작
    - name: Run ls -al
      run: ls -al
    - name: Run build
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_NAME }}
        key: ${{ secrets.SSH_PEM_KEY }}
       # passphrase: ${{ secrets.SSH_PEM_PASSPHRASE }}
        strip_components: 1
        target: ${{ secrets.SERVER_PATH }}
    
